name: "Master Build, Test & Deploy"

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set node version
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install
      run: |
        npm install
        npm run setheapsize

    - name: Lint
      run: npx grunt lint

    - name: Unit Tests
      run: |
        npm test
        npm run testnodeconsumer

    - name: Production Build
      if: success()
      run: npx grunt prod --msg="<a href='skerritt.blog/cyberfork/'>Release Blog Post</a> <a href='http://discord.skerritt.blog'>Discord</a>"

    - name: Generate sitemap
      run: npx grunt exec:sitemap

    - name: UI Tests
      if: success()
      run: |
        sudo apt-get install xvfb
        xvfb-run --server-args="-screen 0 1200x800x24" npx grunt testui

    - name: Prepare for GitHub Pages
      if: success()
      run: npx grunt copy:ghPages

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: ./build/prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
