name: "Pull Requests"

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set node version
        uses: actions/setup-node@v6
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: |
          export DETECT_CHROMEDRIVER_VERSION=true
          npm install
          npm run setheapsize

      - name: Lint
        run: npx grunt lint

      - name: Unit Tests
        run: |
          npm test
          npm run testnodeconsumer

      - name: Production Build
        if: success()
        run: npx grunt prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Production Image Build
        if: success()
        id: build-image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
      - name: UI Tests
        if: success()
        run: |
          sudo apt-get install xvfb
          xvfb-run --server-args="-screen 0 1200x800x24" npx grunt testui
